# Generated by Django 5.1.1 on 2024-09-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='logo',
        ),
        migrations.AddField(
            model_name='about',
            name='icon',
            field=models.CharField(default='empty', max_length=100),
        ),
    ]
